language: python
python:
- '3.5'
services:
- postgres
- redis
install: pip install -r requirements.txt
script: coverage run --omit "*.html" --source blog site_tests.py
after_success:
- coveralls
- ssh-keyscan -H ssh.tomhaines.xyz >> ~/.ssh/known_hosts
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy dokku@ssh.tomhaines.xyz:personal
- git push deploy master
before_install:
- openssl aes-256-cbc -K $encrypted_b4c6c61024e1_key -iv $encrypted_b4c6c61024e1_iv
  -in key.enc -out .travis/deploy_key -d
