"""Fixed migrations

Revision ID: 0b43ed9c1658
Revises: None
Create Date: 2016-10-30 14:32:31.410772

"""

# revision identifiers, used by Alembic.
revision = '0b43ed9c1658'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('datetimeposted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('role', sa.String(length=3), nullable=True),
    sa.Column('is_account_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('blog_post')
    ### end Alembic commands ###
