"""Added user table

Revision ID: c757f3274fd4
Revises: 3c074797f45f
Create Date: 2016-10-30 12:42:18.597596

"""

# revision identifiers, used by Alembic.
revision = 'c757f3274fd4'
down_revision = '3c074797f45f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=3), nullable=True),
    sa.Column('is_account_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
